# Generated by Django 4.2.30 on 2026-06-26 03:03
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ("categories", "0001_initial"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#94a3b8", max_length=7),
        ),
    ]
