# Generated by Django 4.2.30 on 2026-06-26 03:31
from typing import ClassVar

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0002_category_color"),
    ]

    operations: ClassVar = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "user")},
        ),
    ]
