# Generated by Django 4.2.30 on 2026-06-26 03:36
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ("categories", "0003_alter_category_unique_together"),
    ]

    operations: ClassVar = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
    ]
